title: Deep Learning Algorithms
logo: /assets/img/logo.jpg
email: simone.debonis98@gmail.com
description: Learning Algorithms explained in details with math and Numpy.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/SimoneDeBonis
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/simonedebonis/
  - name: Mail
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:simone.debonis98@gmail.com

navigation:
  - name: Neural Networks
    link: ./index.html
    sublist:
      - name: Bayes Classifier
        link: ./index.html#small-image
  - name: Sequence Modeling
    link: ./index.html
    sublist:
      - name: RNN
        link: ./index.html#small-image
      - name: LSTM
        link: ./index.html#small-image
      - name: Transformer
        link: ./index.html#small-image
  - name: CNN
    link: ./KNN.html
